### ISSUE TITLE
Item Physics Mod Should Be Added to Flarial Client 

### ISSUE THREAD

**Issue by xRealAntman** [flarialmc/dll#42] opened 2024-08-14 05:00 UTC
### Feature description

Item Physics is a mod which helps in reducing lag especially when you system is low end basically what is does is when you drop a item or a item is droped it is places flat on ground with no animation it reduces lag very much 

### Reason

```Markdown
this should be added to make the game smooth especially when you are playing bedwars or other mini games which requires FPS
```

**Comment by DankDX** [comment] 2024-08-14 06:41
I already made this #24

**Comment by aShanki** [comment] 2024-08-14 10:03
Closing due to this being a duplicate of #24

**Closed by aShanki** 2024-08-14 10:03 UTC
Labels: enhancement
